// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joiunavbqgulbqzpdmkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaXVuYXZicWd1bGJxenBkbWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDIxNzAsImV4cCI6MjA2MDQ3ODE3MH0.BShC8dDSxzbghr-36PS3pMPfuOkaW0NAKBOidysfWuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);